Adding the DetailsPageHighlights component
carbon-design-system/carbon-addons-catalog-react pull request #1
Opened 2017-06-29 20:06 UTC by aditirajagopal

Implemented the Carbon equivalent of https://github.ibm.com/Bluemix/Bluemix.Catalog/blob/master/render-src/components/DetailsPageHighlights.js

To Do: Get feedback, figure out unit tests & scss cleanup

Signed-off-by: Aditi Rajagopal <arajagopal@us.ibm.com>

2017-07-11 15:11 UTC, jrpomeroy commented
@chrisdhanaraj Any way you could take a look at this and provide feedback when you get a minute?  We're hoping to implement this component in our service by end of July so I just want to make sure there is some movement here.  Thanks!

2017-07-11 16:22 UTC, chrisdhanaraj commented
Will do, I'll be taking a look through this today or tomorrow

2017-07-11 18:55 UTC, hellobrian commented on components/DetailsPageHighlights/DetailsPageHighlights.js
> +// import MarkdownRenderer from './MarkdownRenderer'
Can you delete any commented code that may not be needed

2017-07-18 20:33 UTC, chrisdhanaraj requested changes
Same as the other PR - the React itself is mostly fine, but the `scss` needs a lot of cleanup before it can be merged

2017-07-18 20:33 UTC, chrisdhanaraj commented on .eslintignore
> +reverse-proxy
can you remove these? There is no bower_components, coverage, public, or reverse-proxy in this repository

2017-07-18 20:33 UTC, chrisdhanaraj commented on .eslintrc
> +}
similarly remove these - eslintrc configuration will get standardized across all Carbon repos in a different PR

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/DetailsPageHighlights.js
> +import MarkdownRenderer from '../MarkdownRenderer/MarkdownRenderer'
From our other React library, we've been using an `internal` folder for components that aren't really for general consumption. The MarkdownRenderer might belong there instead

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +  & .bx--createArtifactFlexGroupColumn {
why the additional specificity?

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    font-size: 1.55rem;
Elsewhere we use `rem(pixelvalue)` for font-size. Would be good to standardize around that

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    font-weight: 200;
Font-weight: 200 is a deprecated weight, swap to `300` for light and  `400` for regular

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +  @include breakpoint(825px) {
any media query should be embedded in the class that needs it. Additionally (this is new), we're moving away from the `@include breakpoint` to a more standard

`@media (min-width: breakpoint('xs'))`

with the mapping looking like

```
$grid-breakpoints: (sm: 576px, md: 768px, lg: 992px, xl: 1200px, xxl: 1600px);
```

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    & .bx--createArtifactFlexGroupRow {
can you double check the specifity requirements for nesting this class?

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +@media (max-width: 768px) {
Similar point, all media queries should be nested inside the class

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    em {
not required for the `em` tag

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +  font-family: "IBM Helvetica", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
Not required, the `body` tags will handle the font-family

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +  font-size: 0.875em;
We don't use `em` units here

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +  line-height: 1.2858;
What does this line-height correspond to

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +  width: 100%;
Block elements are natively 100% width, unnecessary scss

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    justify-content: flex-start;
flex-start is the initial starting property for `justify-content`, no need to describe it here

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    font-family: "IBM Helvetica", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
Unnecessary font-family tag

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/MarkdownRenderer/markdownrenderer.scss
> +        .underline-text {
looks like this class is getting reused / redefined a couple times

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/MarkdownRenderer/markdownrenderer.scss
> +        .underline-text {
(from the previous scss sheet above), same scss

2017-07-18 20:33 UTC, chrisdhanaraj commented on components/MarkdownRenderer/markdownrenderer.scss
> +        strong {
not required

2017-07-18 20:33 UTC, chrisdhanaraj commented on package.json
> +    "babel-eslint": "^6.0.3",
remove the linting dev changes done here

2017-07-25 20:57 UTC, davidmenendez commented
@chrisdhanaraj can you review the latest changes?

2017-07-27 14:38 UTC, chrisdhanaraj requested changes
Apologies for the delay, couple more clean up things here.

2017-07-27 14:38 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    p {
We don't style elements directly, always through classes. This let's us flex the element type if need be in the future

2017-07-27 14:38 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +      ul {
You're at four levels of specifity here, we cap Carbon at three unless there's a _really_ good reason. I'd look at refactoring and applying the BEM principles to simplify the CSS structure

2017-07-27 14:38 UTC, chrisdhanaraj commented on components/DetailsPageHighlights/detailspagehighlights.scss
> +    @media screen and (min-width: 825px) {
Can you see if you can adjust this to one of the breakpoints we already define

2017-07-27 14:38 UTC, chrisdhanaraj commented on .storybook/webpack.config.js
> +const webpack = require("webpack");
Why is this being added in?

2017-07-28 20:21 UTC, aditirajagopal commented
@chrisdhanaraj updated based on your comments

2017-08-01 14:04 UTC, chrisdhanaraj commented
👍

2017-08-01 14:04 UTC, chrisdhanaraj approved these changes

2017-08-01 14:04 UTC, merged